name: project
description: "Campus Food Waste Connector - Surplus Food Sharing App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  
  # State Management
  provider: ^6.1.2
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  
  # Image Picker
  image_picker: ^1.1.2
  
  # Location & Maps
  geolocator: ^14.0.2
  google_maps_flutter: ^2.9.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
